[programs.localnet]
halffin = "28Y6Ezy4za168iKHsWb1iUih7pDw1NzBWFJ4Kya8FmQb"

[programs.devnet]
halffin = "28Y6Ezy4za168iKHsWb1iUih7pDw1NzBWFJ4Kya8FmQb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/supasinliulaks/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
